name: Deploy Bengali Text Summarizer

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

# Define the required permissions for GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment workflow runs at a time
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Enables caching of npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build
        env:
          # Set the base path for asset references in the build
          NEXT_PUBLIC_BASE_PATH: '/bengali-text-summarizer'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out  # Directory containing the built static files

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # Ensures the build job completes before deploying
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
